-- 01_schema.sql
CREATE DATABASE IF NOT EXISTS ubicua_db;
USE ubicua_db;

CREATE TABLE IF NOT EXISTS SENSOR_DATA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    temperature FLOAT,
    humidity FLOAT,
    light INT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);